import streamlit as st
from dotenv import load_dotenv
from pathlib import Path
from itinerary import weathercheck, genItinerary
from affiliate import city_to_id, gyg_banner

# Load environment variables from the .env file in this project directory
env_path = Path(__file__).resolve().parent / ".env"
load_dotenv(dotenv_path=env_path, override=True)

st.set_page_config(page_title="AI Trip Planner", page_icon="🗺️", layout="wide")

# Header
st.title("AI Trip Planner 🗺️")
st.caption(
    "Type a city to see live weather, get AI-powered trip ideas, "
    "and discover bookable activities via GetYourGuide."
)

with st.container():
    st.markdown("### Plan your next day out")
    city = st.text_input("City", placeholder="Try London, Lisbon, Dubai...")

    col_btn, col_hint = st.columns([1, 2])
    with col_btn:
        go_clicked = st.button("Get itinerary", type="primary")
    with col_hint:
        st.write(
            "Tip: Start with a major city that you know "
            "is likely to have tours on GetYourGuide."
        )

if go_clicked:
    if not city:
        st.warning("Please enter a city name first.")
    else:
        try:
            weather = weathercheck(city)
        except RuntimeError as e:
            st.error(str(e))
            st.stop()

        # Two-column layout: weather on the left, AI ideas + GYG widget on the right
        left_col, right_col = st.columns([1, 1], gap="large")

        with left_col:
            st.markdown("### 🌤 Weather overview")
            top_row_1, top_row_2 = st.columns([3, 1])

            with top_row_1:
                st.subheader(f"{city.title()}")
                st.write(
                    f"**{weather['temp_c']}°C** (feels like **{weather['feels_like']}°C**), "
                    f"{weather['conditions']}."
                )
                st.write(f"Humidity: **{weather['humidity']}%**")

            with top_row_2:
                icon_url = f"https://openweathermap.org/img/wn/{weather['icon']}@2x.png"
                st.image(icon_url, width=64)

        with right_col:
            st.markdown("### 💡 AI trip ideas")
            try:
                with st.spinner("Thinking of ideas for today’s weather..."):
                    reply = genItinerary(city, weather)
                st.markdown("#### Suggestions for your day")
                st.write(reply)
                st.caption(
                    "These ideas are generated by AI and based on the current weather. "
                    "Always check opening times and availability before you go."
                )
            except RuntimeError as e:
                st.error(str(e))

            st.markdown("### 🎟 Bookable activities")
            gyg_banner(city)

st.markdown("""
---
<div style='text-align: center; font-size: 0.9em; color: gray;'>
Built by Pav · Made to help others learn Python, APIs, Gen AI, Prompt Engineering & Streamlit. <a href="https://github.com/codewithpav/weather-gyg-app/blob/main/readme.md" target="_blank">Follow the step-by-step beginner guide</a>
</div>
</div>
""", unsafe_allow_html=True)